openapi: 3.0.0
info:
  title: Users API
  version: 1.0.0
  description: API para la gestión de usuarios.
servers:
  - url: http://localhost:3000/api
paths:
  /users:
    get:
      summary: Obtiene todos los usuarios
      description: Retorna una lista de todos los usuarios registrados.
      responses:
        "200":
          description: Lista de usuarios obtenida con éxito
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: success
                  payload:
                    type: array
                    items:
                      type: object
                      properties:
                        _id:
                          type: string
                          example: "6764ffa25908115ed12566b1"
                        first_name:
                          type: string
                          example: Zoila
                        last_name:
                          type: string
                          example: Walker
                        email:
                          type: string
                          example: Clotilde.Sawayn44@gmail.com
                        password:
                          type: string
                          example: $2b$10$c9TTexcmnT6x1V4eYgLqc.aqjez5C/eIEsR6EQjPA.xE8n5Md9WQm
                        role:
                          type: string
                          example: admin
                        pets:
                          type: array
                          items:
                            type: object
                            properties:
                              _id:
                                type: string
                                example: "6736be95c5b2fffcaca242e2"
                        __v:
                          type: integer
                          example: 0
        "500":
          description: Error del servidor
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: error
                  error:
                    type: string
                    example: Internal Server Error

  /users/{uid}:
    get:
      summary: Obtiene un usuario por ID
      description: Retorna los detalles de un usuario específico.
      parameters:
        - name: uid
          in: path
          required: true
          description: ID del usuario a obtener
          schema:
            type: string
      responses:
        "200":
          description: Usuario obtenido con éxito
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: success
                  payload:
                    type: object
                    properties:
                      _id:
                        type: string
                        example: "6764ffa25908115ed12566b1"
                      first_name:
                        type: string
                        example: Zoila
                      last_name:
                        type: string
                        example: Walker
                      email:
                        type: string
                        example: Clotilde.Sawayn44@gmail.com
                      password:
                        type: string
                        example: $2b$10$c9TTexcmnT6x1V4eYgLqc.aqjez5C/eIEsR6EQjPA.xE8n5Md9WQm
                      role:
                        type: string
                        example: admin
                      pets:
                        type: array
                        items:
                          type: object
                          properties:
                            _id:
                              type: string
                              example: "6736be95c5b2fffcaca242e2"
                      __v:
                        type: integer
                        example: 0
        "404":
          description: Usuario no encontrado
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: error
                  error:
                    type: string
                    example: User not found
        "500":
          description: Error del servidor
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: error
                  error:
                    type: string
                    example: Internal Server Error

    put:
      summary: Actualiza un usuario por ID
      description: Permite actualizar los datos de un usuario existente.
      parameters:
        - name: uid
          in: path
          required: true
          description: ID del usuario a actualizar
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                first_name:
                  type: string
                  example: Zoila
                last_name:
                  type: string
                  example: Walker
                email:
                  type: string
                  example: Clotilde.Sawayn44@gmail.com
                role:
                  type: string
                  enum: [admin, user]
                  example: admin
      responses:
        "200":
          description: Usuario actualizado con éxito
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: success
                  message:
                    type: string
                    example: User updated
        "404":
          description: Usuario no encontrado
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: error
                  error:
                    type: string
                    example: User not found
        "500":
          description: Error del servidor
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: error
                  error:
                    type: string
                    example: Internal Server Error

    delete:
      summary: Elimina un usuario por ID
      description: Elimina un usuario específico según su ID.
      parameters:
        - name: uid
          in: path
          required: true
          schema:
            type: string
          description: ID del usuario
      responses:
        "200":
          description: Usuario eliminado
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: success
                  message:
                    type: string
                    example: User deleted
        "404":
          description: Usuario no encontrado
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: error
                  error:
                    type: string
                    example: User not found
